### PR TITLE
Big refactor: remove Insights data source and raw data support

### PR DESCRIPTION
**Pull request by emi420**
#### Removed Inisights as a data source

This PR includes the remove of all references to Insights, leaving [Underpass](https://github.com/hotosm/underpass) as the only data source for statistics. The main reason for this is that Insights will be turned off soon.

#### Removed Raw data features

This feature was moved to a new exciting project: [Export Tool](https://github.com/hotosm/osm-export-tool). All functionality related to Raw Data was removed in this PR.

### CODE REVIEW

**Comment by kshitijrajsharma** [comment]
Thanks Emi ! Huge PR ! I will suggest having tests on endpoints level like [this](https://github.com/hotosm/export-tool-api/blob/develop/tests/test_API.py).  So that we will know if anything is breakable by PR from end user perspective ! , I will go through the PR

**Review by kshitijrajsharma — CHANGES_REQUESTED** [review]
Action Items : 

- [x] Hashtag Stats Endpoints Doesn't work , PR is still referring to insight's hashtag table  [IMP]

In my computer Query are very slow for user stats / Mapathon detail of one week time period , may be we can work on speed , could be because of my ssh tunnel but yeah we can verify 

We should add sample request on  docs for dataquality endpoints  

Other than that I can run the API and run the endpoints with no issues

**Comment by emi420** [comment]
> Action Items :
>     * [x]  Hashtag Stats Endpoints Doesn't work , PR is still referring to insight's hashtag table  [IMP]

Done here:

https://github.com/hotosm/galaxy-api/pull/356/commits/672e618cd0cc8a1dba6234fcd2633105720bd88d

CC @kshitijrajsharma

**Review by kshitijrajsharma — APPROVED** [review]
Good to Go !

**Comment by kshitijrajsharma** [comment]
I have approved the PR ! to avoid blockage of implementation but query for hashtag statistics should be revised and also the response 

hashtag statistics provides result in summarised view like this 
```
[
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-10-23",
    "endDate": "2020-10-30",
    "totalNewBuildings": 7937,
    "totalUniqueContributors": 80,
    "totalNewRoadMeters": 15376,
    "totalNewAmenities": 33,
    "totalNewPlaces": 3
},
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-10-30",
    "endDate": "2020-11-06",
    "totalNewBuildings": 12744,
    "totalUniqueContributors": 116,
    "totalNewRoadMeters": 38274,
    "totalNewAmenities": 2,
    "totalNewPlaces": 0
},
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-11-06",
    "endDate": "2020-11-13",
    "totalNewBuildings": 9147,
    "totalUniqueContributors": 52,
    "totalNewRoadMeters": 31882,
    "totalNewAmenities": 0,
    "totalNewPlaces": 1
},
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-11-13",
    "endDate": "2020-11-20",
    "totalNewBuildings": 41900,
    "totalUniqueContributors": 371,
    "totalNewRoadMeters": 19981,
    "totalNewAmenities": 79,
    "totalNewPlaces": 16
},
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-11-20",
    "endDate": "2020-11-27",
    "totalNewBuildings": 26645,
    "totalUniqueContributors": 152,
    "totalNewRoadMeters": 85923,
    "totalNewAmenities": 6,
    "totalNewPlaces": 1
},
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-11-27",
    "endDate": "2020-12-04",
    "totalNewBuildings": 31186,
    "totalUniqueContributors": 228,
    "totalNewRoadMeters": 27537,
    "totalNewAmenities": 54,
    "totalNewPlaces": 0
},
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-12-04",
    "endDate": "2020-12-11",
    "totalNewBuildings": 35996,
    "totalUniqueContributors": 206,
    "totalNewRoadMeters": 83153,
    "totalNewAmenities": 0,
    "totalNewPlaces": 1
},
{
    "hashtag": "msf",
    "frequency": "w",
    "startDate": "2020-12-11",
    "endDate": "2020-12-18",
    "totalNewBuildings": 27088,
    "totalUniqueContributors": 70,
    "totalNewRoadMeters": 261235,
    "totalNewAmenities": 0,
    "totalNewPlaces": 0
}
]
```
Currently I am getting null response as back for this request 
```
{ "hashtag": "missingmap", "frequency": "w", "outputType": "json", "startDate": "2020-10-22", "endDate": "2020-12-22" }
```
 I have ignored it for now since we are not working on accurate stats but I will recommend turning off this endpoint for now and enabling it after heiget comes in 
 cc: @emi420  @ramyaragupathy

**Comment by kshitijrajsharma** [comment]
I have approved the PR , for previous case scenario i am getting null responses such as. 
```
{ "hashtag": "msf", "frequency": "w", "outputType": "json", "startDate": "2020-10-22", "endDate": "2020-12-22" }
```
But I have ignored them for now since we are not working on accurate stats . Rest looks Good ! Great work !

**Comment by kshitijrajsharma** [comment]
I have approved the PR , for few case scenario i am getting null responses such as. 
```
{ "hashtag": "msf", "frequency": "w", "outputType": "json", "startDate": "2020-10-22", "endDate": "2020-12-22" }
```
Which is okay and negligible ,  Rest looks Good ! Great work !

**Comment by emi420** [comment]
> I have approved the PR , for few case scenario i am getting null responses such as.
> 
> ```
> { "hashtag": "msf", "frequency": "w", "outputType": "json", "startDate": "2020-10-22", "endDate": "2020-12-22" }
> ```
> 
> Which is okay and negligible , Rest looks Good ! Great work !

The query looks good, it's just that data is missing in the DB for those dates, I'll start a process soon to fill what's is missing.

**Pull request merged**
