### PR TITLE
Endpoint for ogranization hashtag stats

### LINKED ISSUE #107: API Endpoint for Ogranization Hashtag Statistics
Given a hashtag and a weekly/monthly frequency return key feature and user statistics for the hashtag
**Data Source:** Insights
**Sample request body:**
{
    hashtag: [“hashtag_1”, “hashtag_2”],
    frequency: “w”/”m”
}

**Acceptance Criteria:**
    • User provides a set of hashtags 
        ◦ Array of strings
        ◦ If this is null throw a 402 error with an appropriate error message
        ◦ Required parameter
    • Frequency:
        ◦ Allowed values in string: “w”/”m”
        ◦ Other values throws a 402 error
        ◦ Required parameter
    • Output Type:
        ◦ CSV/JSON
    • CSV
        ◦ Hashtag|frequency|start_date|end_date|total_new_buildings|total_unique_contributors|total_new_road_kms
    • JSON
{
  { "hashtag": “msf”, 
  "frequency": "w", 
  “start_date”:,
  “end_date”: ,
  “total_new_buildings”: ,
  “total_unique_contributors”:,
  “total_new_road_kms”:
   },
  { "hashtag": “msf”, 
  "frequency": "w", 
  “start_date”:
  “end_date”: ,
  “total_new_buildings”: ,
  “total_unique_contributors”:,
  “total_new_road_kms”:
  },
   { "hashtag": “msflondon”, 
  "frequency": "w", 
  “start_date”:,
  “end_date”: ,
  “total_new_buildings”: 
  “total_unique_contributors”:
  “total_new_road_kms”:
  }
}

### LINKED ISSUE #112: Make Hashtag parameter case insensitive
The parameter are case sensitive, while the hashtags are stored and calculated in non sensitive cases .. It is recommended to have the API search for non case sensitive hashtags even if the API request has CAPS..

_Originally posted by @omranlm in https://github.com/hotosm/galaxy-api/pull/108#pullrequestreview-839283016_

### PR DESCRIPTION
**Pull request by kshitijrajsharma**
- Resolve #107 
- Resolve #112

### CODE REVIEW

**Review by omranlm — CHANGES_REQUESTED** [review]
The parameter are case sensitive, while the hashtags are stored and calculated in non sensitive cases .. It is recommended to have the API search for non case sensitive hashtags even if the API request has CAPS..

**Comment by omranlm** [comment]
When passing the following input
```
{
  "hashtags": [
    "missingmaps"
  ],
  "frequency": "w",
  "outputType": "json",
  "endDate": "2021-12-23"
}
```
the expected output is all missingmaps stats since beginning till end date , but it gives an error 

```
Error: Unprocessable Entity
Response body
{
  "detail": [
    {
      "loc": [
        "body",
        "endDate"
      ],
      "msg": "unsupported operand type(s) for -: 'datetime.date' and 'NoneType'",
      "type": "type_error"
    }
  ]
}
```

**Comment by omranlm** [comment]
For input such as 
```
{
  "hashtags": [
    "missingmaps","msf","11682"
  ],
  "frequency": "w",
  "outputType": "json"
}
```
the results are returned for hastags  "missingmaps","msf" and for HOT TM project ID "11682" so the hashtag is "hotosm-project-11682" is used when calculating the stats.. we have 2 options to make it clear result:
1- Even add in the results a flag isTMProject = true/false by modifying the query and adding isTMProject to the select 
2- when returning the stats for a TM project, return the value hashtag:"hotosm-project-11682" for HOT TM projects

CC @ramyaragupathy  for which direction make more sense

**Comment by omranlm** [comment]
the results total new roads value is returned in meters not KM, we can divide by 1000 on the API level or rename the results field to ne totalNewRoadMeters 
@itskshitiz321

**Comment by itskshitiz321** [comment]
> the results total new roads value is returned in meters not KM, we can divide by 1000 on the API level or rename the results field to ne totalNewRoadMeters @itskshitiz
In that case we need to update  rename column in our hashtag_stats table as well , it should be total_new_road_m @omranlm

**Comment by ramyaragupathy** [comment]
@Kshitij @Omran Najjar - I believe the hashtags that we supply here should have an exact match in the DB - so if it is `11682` it has to look for `11682` not for `hotosm-project-11682`. There is no need for a TM specific switch here.

**Review by omranlm — APPROVED** [review]
Looks great, I tested the end point and results as well with different scenarios 
such as input for quarterly values with CAPS and small, empty spaces and none existing hashtags 
```
{
  "hashtags": [
    "mapsouthkivU ","rrr"
  ],
  "frequency": "q",
  "outputType": "json",
  "endDate": "2021-05-01"
}
```

**Pull request merged**
